language: perl
matrix:
  include:
  - name: "openSUSE/SUSE production perl version, only compile check"
    perl: "5.18"
    env: TESTS=compile
  - name: "testing perl version, all tests"
    perl: "5.26"
    env: TESTS=all
env:
  global:
    - COMMIT_AUTHOR_EMAIL=skynet@open.qa
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libssh2-1-dev
      - parallel
cache:
  directories:
    - $HOME/perl5
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl --always-upgrade-modules
  - echo "requires 'Code::DRY';" >> cpanfile
  - echo "requires 'Perl::Tidy', '== 20181120';" >> cpanfile
install:
  - make prepare
script:
  - git checkout cpanfile
  - make test
before_deploy:
  - script/generateUtilsDoc.sh
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local-dir: $TRAVIS_BUILD_DIR/docs/
    on:
        branch: master
    target_branch: gh-pages

